version: 2
project_name: terraform-provider-tfcoolify
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like HCP Terraform where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  draft: true
  replace_existing_draft: true
  footer: |
    **Full Changelog**: https://github.com/codefunded/terraform-provider-tfcoolify/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^ci:"
      - "^ci\\("
      - "^build:"
      - "^build\\("
      - "^chore\\(deps\\):" # dev tools only
      - "^(docs|chore)\\(git\\):" # repo maintenance nobody cares about
      - "^merge"
      - "^Merge"
      - "\\btypos?\\b" # typos are not interesting
  groups:
    - title: ⚠️ Breaking Changes
      regexp: "^.*\\w[(\\w)]*!:+.*$"
      order: 0
    - title: ✨ New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 🔒 Security updates
      regexp: "^.*\\[(?i)SECURITY\\]$"
      order: 150
    - title: 📦 Dependency updates
      regexp: "^.*(feat|fix)\\(deps\\)*:+.*$"
      order: 450
    - title: 🐛 Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 📝 Documentation updates
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: 🔧 Build process updates
      regexp: "^.*?(build|ci)[(\\w)]*:+.*$"
      order: 500
    - title: 📑 Other changes
      order: 9999
